### ISSUE TITLE
rake punching_bag:combine fails with error: "undefined method `starts_at' for nil:NilClass"

### ISSUE THREAD

**Issue by hoff2** [biola/punching_bag#8]
````
** Invoke punching_bag:combine (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute punching_bag:combine
rake aborted!
undefined method `starts_at' for nil:NilClass
/var/www/sites/finditatthemall.com/shared/bundle/ruby/1.9.1/gems/punching_bag-0.3.5/app/models/punch.rb:63:in `combine_with'
/var/www/sites/finditatthemall.com/shared/bundle/ruby/1.9.1/gems/punching_bag-0.3.5/app/models/punch.rb:74:in `combine_by_day'
/var/www/sites/finditatthemall.com/shared/bundle/ruby/1.9.1/gems/punching_bag-0.3.5/lib/tasks/punching_bag.rake:26:in `block (5 levels) in <top (required)>'
/var/www/sites/finditatthemall.com/shared/bundle/ruby/1.9.1/gems/activerecord-3.2.13/lib/active_record/relation/delegation.rb:6:in `each'
/var/www/sites/finditatthemall.com/shared/bundle/ruby/1.9.1/gems/activerecord-3.2.13/lib/active_record/relation/delegation.rb:6:in `each'
/var/www/sites/finditatthemall.com/shared/bundle/ruby/1.9.1/gems/punching_bag-0.3.5/lib/tasks/punching_bag.rake:25:in `block (4 levels) in <top (required)>'
/var/www/sites/finditatthemall.com/shared/bundle/ruby/1.9.1/gems/punching_bag-0.3.5/lib/tasks/punching_bag.rake:11:in `each'
/var/www/sites/finditatthemall.com/shared/bundle/ruby/1.9.1/gems/punching_bag-0.3.5/lib/tasks/punching_bag.rake:11:in `block (3 levels) in <top (required)>'
/var/www/sites/finditatthemall.com/shared/bundle/ruby/1.9.1/gems/punching_bag-0.3.5/lib/tasks/punching_bag.rake:8:in `each'
/var/www/sites/finditatthemall.com/shared/bundle/ruby/1.9.1/gems/punching_bag-0.3.5/lib/tasks/punching_bag.rake:8:in `block (2 levels) in <top (required)>'
/var/www/sites/finditatthemall.com/shared/bundle/ruby/1.9.1/gems/rake-10.1.0/lib/rake/task.rb:236:in `call'
/var/www/sites/finditatthemall.com/shared/bundle/ruby/1.9.1/gems/rake-10.1.0/lib/rake/task.rb:236:in `block in execute'
/var/www/sites/finditatthemall.com/shared/bundle/ruby/1.9.1/gems/rake-10.1.0/lib/rake/task.rb:231:in `each'
/var/www/sites/finditatthemall.com/shared/bundle/ruby/1.9.1/gems/rake-10.1.0/lib/rake/task.rb:231:in `execute'
/var/www/sites/finditatthemall.com/shared/bundle/ruby/1.9.1/gems/rake-10.1.0/lib/rake/task.rb:175:in `block in invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/var/www/sites/finditatthemall.com/shared/bundle/ruby/1.9.1/gems/rake-10.1.0/lib/rake/task.rb:168:in `invoke_with_call_chain'
/var/www/sites/finditatthemall.com/shared/bundle/ruby/1.9.1/gems/rake-10.1.0/lib/rake/task.rb:161:in `invoke'
/var/www/sites/finditatthemall.com/shared/bundle/ruby/1.9.1/gems/rake-10.1.0/lib/rake/application.rb:149:in `invoke_task'
/var/www/sites/finditatthemall.com/shared/bundle/ruby/1.9.1/gems/rake-10.1.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/var/www/sites/finditatthemall.com/shared/bundle/ruby/1.9.1/gems/rake-10.1.0/lib/rake/application.rb:106:in `each'
/var/www/sites/finditatthemall.com/shared/bundle/ruby/1.9.1/gems/rake-10.1.0/lib/rake/application.rb:106:in `block in top_level'
/var/www/sites/finditatthemall.com/shared/bundle/ruby/1.9.1/gems/rake-10.1.0/lib/rake/application.rb:115:in `run_with_threads'
/var/www/sites/finditatthemall.com/shared/bundle/ruby/1.9.1/gems/rake-10.1.0/lib/rake/application.rb:100:in `top_level'
/var/www/sites/finditatthemall.com/shared/bundle/ruby/1.9.1/gems/rake-10.1.0/lib/rake/application.rb:78:in `block in run'
/var/www/sites/finditatthemall.com/shared/bundle/ruby/1.9.1/gems/rake-10.1.0/lib/rake/application.rb:165:in `standard_exception_handling'
/var/www/sites/finditatthemall.com/shared/bundle/ruby/1.9.1/gems/rake-10.1.0/lib/rake/application.rb:75:in `run'
/var/www/sites/finditatthemall.com/shared/bundle/ruby/1.9.1/gems/rake-10.1.0/bin/rake:33:in `<top (required)>'
/var/www/sites/finditatthemall.com/shared/bundle/ruby/1.9.1/bin/rake:23:in `load'
/var/www/sites/finditatthemall.com/shared/bundle/ruby/1.9.1/bin/rake:23:in `<main>'

**Comment by tastemeru** [comment]
RAILS_ENV=production rake punching_bag:combine --trace
```
** Invoke punching_bag:combine (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute punching_bag:combine
rake aborted!
ActiveRecord::StatementInvalid: PG::InvalidColumnReference: ERROR:  for SELECT DISTINCT, ORDER BY expressions must appear in select list
LINE 1: ...unches"."punchable_type" FROM "punches"  ORDER BY punches.av...
                                                             ^
: SELECT DISTINCT "punches"."punchable_type" FROM "punches"  ORDER BY punches.average_time DESC
```

**Comment by adamcrown** [comment]
@hoff2 @pywebdesign I apologize that it's been so very long. I realize I've neglected this project a bit but I'm going to try to keep on top of it better. Are either of you still experiencing this problem?

@tastemeru It looks like you have a different issue, something likely related to your database or maybe to PostgreSQL support. Could you open a separate issue please?

**Comment by adamcrown** [comment]
It's been about a month with no response to this. So I'm closing it. If either of your are still having trouble, just let me know and I'll reopen it.

**Comment by hoff2** [comment]
Yeah sorry -- I haven't been on that project since a couple years ago.
